# 01 Introduccion a NumPY

### 1. Importar libreria numpy

>>  _import numpy as np_


### 2. crear un array de numpy

> _arr = [1,2,3,4]_ <br>
> _numpy = np.array(arr)_

In [2]:
import numpy as np


arr = [1,2,3,4]
np.array(arr)

array([1, 2, 3, 4])

### 3.  Array bidimensional

> _bi_arr = [[1,2],[3,4],[5,6]]_ <br>
>  _np.array(bi_arr)_

In [3]:
bi_arr = [[1,2],[3,4],[5,6]]
np.array(bi_arr)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 4. Rangos de Numeros

_print(np.arange(10))_

_print(np.arange(1,10))_

_print(np.arange(0,10,2))_

In [ ]:
np.arange(10)

### 5. Vector de Ceros y Unos

_print(np.zeros(3))_

_print(np.ones(3))_

### 6. Matriz de ceros y unos
_print(np.ones((3,4)))_

### 7. Matriz Identidad
_print(np.eye(5))_

### 8. Dividir Rango en n valores

_print(np.linspace(0,10,3))_  <br>

_print(np.linspace(0,10,20))_

### 9. Numeros aleatorios
_print(np.random.rand(10))_

_print(np.random.rand(3,4))_

_print(np.random.randn(10))_

_print(np.random.randn(3,4))_

_print(np.random.randint(1,100,10))_

_print(np.random.randint(1,100,(2,3)))_


In [3]:
np.random.rand(10)

array([0.60014806, 0.42079661, 0.02393295, 0.33433515, 0.2160542 ,
       0.99128167, 0.72781068, 0.74325389, 0.11786988, 0.42893521])

In [6]:
np.random.randint(10, 100, 50)

array([41, 84, 46, 72, 21, 86, 22, 65, 97, 56, 15, 94, 33, 83, 83, 37, 70,
       93, 56, 52, 82, 39, 13, 82, 25, 24, 78, 29, 23, 46, 24, 58, 75, 91,
       60, 31, 54, 90, 15, 18, 26, 57, 87, 99, 84, 88, 89, 40, 38, 59])

In [8]:
np.random.randint(10, 100, (5,5))

array([[56, 78, 76, 83, 67],
       [74, 84, 79, 34, 83],
       [88, 32, 85, 74, 69],
       [88, 32, 30, 12, 88],
       [59, 77, 50, 52, 24]])

### 10. Numeros aleatorios con semilla

_np.random.seed(42)_

_print(np.random.rand(4))_

In [9]:
np.random.seed(42)