# Tarea 2 - Numpy

> lea detalladamente el ejercicio antes de responder los ejercicios

1. Crear los siguientes arregos de numpy
> * Crear un array con 10 elementos 
> * Crear un array con 5 numeros decimales
> * crear un array de 20 elementos con solo  numeros pares

In [10]:
#import numpy as np
#crear un array con 10 elementos 

array_aleatorio = np.random.rand(10)
print(array_aleatorio)

#crear un array con 5 numeros decimales

array_decimal = np.random.rand(5)
print(array_decimal)

#crear un array de 20 elementos con solo numeros pares

array_pares =np.arange(0, 40 ,2)
print(array_pares)

[0.87346907 0.60517732 0.4823284  0.13026958 0.91170769 0.11338843
 0.57321282 0.59186655 0.7530285  0.98035248]
[0.41418413 0.99989187 0.26226393 0.47491329 0.29617212]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


2. Cual es la forma correcta de crear un Array
> * A) np.createArray([1,2,3,4,5])
> * B) np.object([1,2,3,4,5])
> * C) np.array([1,2,3,4,5])

In [11]:
# C
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

3. Cual es la forma correcta de saber el numero de dimensiones de un array
> * arr.ndim()
> * arr.dim()   
> * arr.ndim
> * arr.dim

In [ ]:
arr.ndim

4. Cual es la sintaxis correcta para imprimir el primer item de un array
> * print(arr,1)
> * print(arr[1])
> * print(arr[0]) 

In [ ]:
print(arr[0])

5. Cual es la sintaxis correcta para imprimir el numero 8 del vector
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
> * print(arr(1,2))
> * print(arr(7,2))
> * print(arr(3,0))

In [ ]:
print(arr(1,2))

6. Cual es la sintaxis correcta para imprimir [3, 4, 5] del array 
arr = np.array([1,2,3,4,5,6,7])
> * print(arr[3:6])
> * print(arr[2:5])
> * print(arr[2:6])
> * print(arr[2:4])

In [ ]:
print(arr[2:5])

7. Crear un vector con valores dentro del rango 10 a 49

In [12]:
#7:Flavio Cesar Flores
arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Invertir el vector creado en la pregunta anterior

In [13]:
#8: Flavio Cesar Flores
arr = np.arange(10, 50)
arr_invertido = arr[::-1]
print(arr_invertido)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]



9. Crear una matriz 3x3 con valores de 0 a 8

In [14]:
#9: Flavio Cesar Flores
matrix = np.arange(9).reshape(3, 3)
print(matrix)


NameError: name 'matriz' is not defined

10. Crear una matriz identidad de 6x6

In [ ]:
#10: Flavio Cesar Flores
matrix_identidad = np.eye(6)
print(matrix_identidad)


11. Encontrar los valores que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

12. Crear una matriz con valores al azar con forma 3x3x3

13. Crear una matriz de 10x10 con 1's en los bordes y cualquier valor en el interior(investigar)

14. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4(investigar)

15. Crear dos arreglos al azar(valores aleatorios) A y B, verificar si son iguales

16. Crear una matrices 10x10 mostrar las siguiente:
> * mostrar las filas 5 en adelante
> * mostrar solo las tres primeras filas
> * mostrar solo las filas 3 a la 7 

17. Crear una matrices 10x10 con valores aleatorios enteros y calcular la suma de valores siguiente:
> * Calcular la suma de todos valores que sean mayores a 25
> * Calcular la suma de los valores por filas que sean mayores a 10 y menores a 25
> * Calcular la suma de los valores por columnas que sean mayores a 50 y menores a 75